import * as cheerio from "cheerio";
import type { CandidateElement } from "../core/parser/index.js";
import { logger } from "../utils/logger.js";

export interface ValidationResult {
  isValid: boolean;
  errorType?: "syntax" | "not_found" | "not_unique" | "mismatch";
  errorMessage?: string;
}

export class ValidationAgent {
  /**
   * Validates a suggested CSS selector or XPath locator against the DOM context.
   * Checks for syntax errors, element existence, uniqueness, and target matching.
   * 
   * @param html The original HTML document.
   * @param targetCandidate The candidate element we are attempting to heal.
   * @param suggestedLocator The selector string generated by the AI.
   */
  validate(
    html: string,
    targetCandidate: CandidateElement,
    suggestedLocator: string
  ): ValidationResult {
    logger.info(`Validating suggested locator: "${suggestedLocator}" against HTML context...`);

    if (!html || html.trim() === "") {
      return {
        isValid: false,
        errorType: "not_found",
        errorMessage: "HTML document is empty.",
      };
    }

    const $ = cheerio.load(html);
    let matchedElements: cheerio.Cheerio<any>;
    const isXPath = suggestedLocator.startsWith("/") || suggestedLocator.startsWith("(");

    try {
      if (isXPath) {
        matchedElements = this.evaluateXPath($, suggestedLocator);
      } else {
        matchedElements = $(suggestedLocator);
      }
    } catch (err: any) {
      logger.warn(`Syntax or execution error in suggested locator: ${err.message}`);
      return {
        isValid: false,
        errorType: "syntax",
        errorMessage: `The locator "${suggestedLocator}" is syntactically invalid or failed to run: ${err.message}`,
      };
    }

    const count = matchedElements.length;
    if (count === 0) {
      logger.warn(`Suggested locator "${suggestedLocator}" matched 0 elements.`);
      return {
        isValid: false,
        errorType: "not_found",
        errorMessage: `The locator "${suggestedLocator}" matched no elements in the current HTML context.`,
      };
    }

    if (count > 1) {
      logger.warn(`Suggested locator "${suggestedLocator}" is not unique. Matched ${count} elements.`);
      return {
        isValid: false,
        errorType: "not_unique",
        errorMessage: `The locator "${suggestedLocator}" is not unique; it matched ${count} different elements in the DOM.`,
      };
    }

    // Uniqueness established. Let's compare matched element with target element
    const matchedEl = matchedElements.first();
    const matchedHtml = $.html(matchedEl);

    const cleanMatched = matchedHtml.replace(/\s+/g, " ").trim();
    const cleanTarget = targetCandidate.htmlSnippet.replace(/\s+/g, " ").trim();

    if (cleanMatched !== cleanTarget) {
      // Perform fallback matching criteria to check if it's logically the same element
      const matchedTag = (matchedEl[0]?.name || "").toUpperCase();
      const targetTag = targetCandidate.tagName.toUpperCase();

      const sameTag = matchedTag === targetTag;
      const sameText = matchedEl.text().replace(/\s+/g, " ").trim() === targetCandidate.text.trim();
      const sameId = matchedEl.attr("id") === targetCandidate.attributes.id;
      const sameTestId = matchedEl.attr("data-testid") === targetCandidate.attributes["data-testid"];

      if (sameTag && (sameText || sameId || sameTestId)) {
        logger.info(`Suggested locator is valid (passed semantic check) and successfully targets candidate.`);
        return { isValid: true };
      }

      logger.warn("Suggested locator matched a different element than the intended candidate.");
      return {
        isValid: false,
        errorType: "mismatch",
        errorMessage: `The locator "${suggestedLocator}" matched a different element in the DOM. Expected: ${cleanTarget.substring(0, 120)}... Matched: ${cleanMatched.substring(0, 120)}...`,
      };
    }

    logger.info(`Suggested locator "${suggestedLocator}" successfully validated against candidate.`);
    return { isValid: true };
  }

  /**
   * Helper utility to evaluate common testing XPaths inside Cheerio.
   */
  private evaluateXPath($: cheerio.CheerioAPI, xpath: string): cheerio.Cheerio<any> {
    // 1. Basic unique attribute selector: //tag[@attr='value'] or //*[@attr='value']
    const attrMatch = xpath.match(/^\/\/([a-zA-Z0-9*-]+)\[@([a-zA-Z0-9*-]+)\s*=\s*['"]([^'"]+)['"]\]$/);
    if (attrMatch) {
      const [, tag, attr, val] = attrMatch;
      const cssSelector = `${tag === "*" ? "" : tag}[${attr}="${val}"]`;
      return $(cssSelector);
    }

    // 2. contains(text(), 'value') selector: //tag[contains(text(), 'value')]
    const containsTextMatch = xpath.match(/^\/\/([a-zA-Z0-9*-]+)\[contains\(text\(\),\s*['"]([^'"]+)['"]\)\]$/);
    if (containsTextMatch) {
      const [, tag, textVal] = containsTextMatch;
      const selector = tag === "*" ? "button, a, input, select, textarea, label, div, span, p, h1, h2, h3" : tag;
      const matches: any[] = [];
      $(selector).each((_, el) => {
        if ($(el).text().includes(textVal)) {
          matches.push(el);
        }
      });
      return $(matches);
    }

    // 3. text()='value' selector: //tag[text()='value']
    const exactTextMatch = xpath.match(/^\/\/([a-zA-Z0-9*-]+)\[text\(\)\s*=\s*['"]([^'"]+)['"]\]$/);
    if (exactTextMatch) {
      const [, tag, textVal] = exactTextMatch;
      const selector = tag === "*" ? "button, a, input, select, textarea, label, div, span, p, h1, h2, h3" : tag;
      const matches: any[] = [];
      $(selector).each((_, el) => {
        if ($(el).text().trim() === textVal.trim()) {
          matches.push(el);
        }
      });
      return $(matches);
    }

    // Fallback: broad tag matching for simple selectors
    const tagOnlyMatch = xpath.match(/^\/\/([a-zA-Z0-9-]+)$/);
    if (tagOnlyMatch) {
      return $(tagOnlyMatch[1]);
    }

    throw new Error(`XPath expression "${xpath}" is too complex for simplified Cheerio execution. Please use a standard attribute or text expression.`);
  }
}
