import { HealerSDK } from "../../sdk/healer.js";
import { parseCandidates } from "../parser/index.js";
import type { CandidateElement } from "../parser/index.js";
import { scoreCandidates } from "../scorer/index.js";
import { generateSelectors } from "../selector/index.js";
import { HealingAgent } from "../../agents/healingAgent.js";
import { ValidationAgent } from "../../agents/validationAgent.js";
import { RetryAgent } from "../../agents/retryAgent.js";
import { logger } from "../../utils/logger.js";

export interface HealedLocatorResult {
  locator: string;
  confidence: number;
  reasoning: string;
  source: "ai" | "heuristic" | "fallback";
  attempts: number;
}

export interface OrchestratorResponse {
  success: boolean;
  healedLocator?: HealedLocatorResult;
  error?: string;
}

export class Orchestrator {
  private sdk: HealerSDK;
  private healingAgent: HealingAgent;
  private validationAgent: ValidationAgent;
  private retryAgent: RetryAgent;

  constructor() {
    this.sdk = new HealerSDK();
    this.healingAgent = new HealingAgent(this.sdk);
    this.validationAgent = new ValidationAgent();
    this.retryAgent = new RetryAgent();
  }

  /**
   * Main orchestrator entry point. Heals a broken locator inside a given HTML context.
   * 
   * @param failedLocator The selector string that failed (e.g. "button#submit").
   * @param failedLocatorMetadata Metadata about the failed locator (tag, text, attributes).
   * @param htmlContext The raw HTML page context at the moment of failure.
   * @param maxRetries Maximum number of agentic retry cycles if validation fails.
   */
  async heal(
    failedLocator: string,
    failedLocatorMetadata: any = {},
    htmlContext: string,
    maxRetries = 3
  ): Promise<OrchestratorResponse> {
    logger.info(`Starting Orchestrator healing process for failed locator: "${failedLocator}"`);

    try {
      // 1. Parse HTML context to extract DOM candidates
      const candidates = parseCandidates(htmlContext);
      if (candidates.length === 0) {
        logger.error("No candidates parsed from HTML context.");
        return {
          success: false,
          error: "Could not find any interactive or attribute-rich candidate elements in the provided HTML context.",
        };
      }

      // 2. Score candidate elements to find the correct target
      const scoredCandidates = scoreCandidates(failedLocator, failedLocatorMetadata, candidates);
      const topScored = scoredCandidates[0];

      if (!topScored || topScored.score < 0.1) {
        logger.warn("No candidate element met the minimum similarity score threshold.");
        return {
          success: false,
          error: "No elements in the current DOM matched the profile of the broken locator closely enough.",
        };
      }

      const targetCandidate = topScored.candidate;
      logger.info(`🎯 Target candidate identified: ${targetCandidate.candidateId} (TagName: ${targetCandidate.tagName}, Similarity Score: ${topScored.score})`);
      logger.info(`Candidate Element Snippet: ${targetCandidate.htmlSnippet}`);

      // Pre-calculate local heuristic fallback selectors for this candidate in case LLM fails
      const heuristicSelectors = generateSelectors(targetCandidate);

      // 3. Agentic Loop (Healing -> Validation -> Retry)
      let validationFeedback = "";
      let attempt = 1;

      while (attempt <= maxRetries) {
        logger.info(`=== Healing Agent Loop Attempt #${attempt}/${maxRetries} ===`);
        
        // Invoke Healing Agent (Groq / Google Gemma-2)
        const agentResponse = await this.healingAgent.heal(
          failedLocator,
          failedLocatorMetadata,
          scoredCandidates.slice(0, 5), // Provide top 5 context matches
          validationFeedback
        );

        if (!agentResponse.success || agentResponse.suggestions.length === 0) {
          logger.warn(`Attempt #${attempt} did not return valid recommendations from the Healing Agent.`);
          attempt++;
          continue;
        }

        // Validate each suggestion generated by the AI
        let currentLoopFeedback = "";
        for (const suggestion of agentResponse.suggestions) {
          const validation = this.validationAgent.validate(htmlContext, targetCandidate, suggestion.locator);
          
          if (validation.isValid) {
            logger.info(`🎉 Success! Healed locator uniquely validated: "${suggestion.locator}" in attempt #${attempt}`);
            return {
              success: true,
              healedLocator: {
                locator: suggestion.locator,
                confidence: suggestion.confidence,
                reasoning: suggestion.reasoning,
                source: "ai",
                attempts: attempt,
              },
            };
          } else {
            // Compile feedback only for the highest confidence failing locator in this loop
            if (!currentLoopFeedback) {
              currentLoopFeedback = this.retryAgent.compileFeedback(attempt, suggestion.locator, validation);
            }
          }
        }

        // Feed back failures to the next loop iteration
        validationFeedback = currentLoopFeedback;
        attempt++;
      }

      // 4. Fallback Heuristic validation if LLM is unable to resolve uniquely
      logger.warn("⚠️ AI Healing Loop failed to validate a unique selector. Falling back to local heuristics...");
      
      for (const localSelector of heuristicSelectors) {
        const validation = this.validationAgent.validate(htmlContext, targetCandidate, localSelector);
        if (validation.isValid) {
          logger.info(`🎉 Success! Locator healed via Local Heuristic selector: "${localSelector}"`);
          return {
            success: true,
            healedLocator: {
              locator: localSelector,
              confidence: 0.75,
              reasoning: "Generated dynamically via native element properties and validated uniquely in DOM context.",
              source: "heuristic",
              attempts: attempt - 1,
            },
          };
        }
      }

      // Absolute Fallback: if uniqueness validation fails, return first heuristic selector best effort
      if (heuristicSelectors.length > 0) {
        const fallbackSel = heuristicSelectors[0];
        logger.warn(`Unvalidated best-effort fallback returned: "${fallbackSel}"`);
        return {
          success: true,
          healedLocator: {
            locator: fallbackSel,
            confidence: 0.35,
            reasoning: "Best-effort fallback generated directly from element attributes. Uniqueness not guaranteed.",
            source: "fallback",
            attempts: attempt - 1,
          },
        };
      }

      return {
        success: false,
        error: "Failed to heal locator: No unique CSS/XPath selector could be validated or generated.",
      };

    } catch (err: any) {
      logger.error(`Orchestrator error: ${err.message}`);
      return {
        success: false,
        error: `An unexpected error occurred during the healing orchestrator process: ${err.message}`,
      };
    }
  }
}
